Reworked LandmarkMapEvaluator
unibas-gravis/scalismo-faces pull request #27
Opened 2017-03-30 15:32 UTC by Andreas-Forster

The `LandmarkMapEvaluator` now works similar to the `LandmarkPointEvaluator`.

- The unspecifc `PixelImage[Double]` were changed to a  class `LandmarkMap`.
- The class can be used directly to correct for the false-positive and false-negative ratios.
- A method is provided to precalculate the map with added noise model using the GeneralMaxConvolution.

2017-03-30 15:57 UTC, sschoenborn requested changes
Great to make landmark detection maps available again and consistent with landmark point evaluators - a few issues remain, however

2017-03-30 15:57 UTC, sschoenborn commented on src/main/scala/scalismo/faces/landmarks/LandmarkDetectionMap.scala
> +class LandmarkDetectionMap(val tag: String, val map: PixelImage[Double]) {
here could be a case class? this is a value type

2017-03-30 15:57 UTC, sschoenborn commented on src/main/scala/scalismo/faces/landmarks/LandmarkDetectionMap.scala
> +  def apply(tag: String, map: PixelImage[Double], fp: Double, fn: Double): LandmarkDetectionMap = {
fp and fn is a bit short to understand without documentation

2017-03-30 15:57 UTC, sschoenborn commented on src/main/scala/scalismo/faces/landmarks/LandmarkDetectionMap.scala
> +  def precalculateIsotropicGaussianNoise(stddevNoiseModel: Double) = {
is the return type another `LandmarkDetectionMap` or a plain `PixelImage`?

2017-03-30 15:57 UTC, sschoenborn commented on src/main/scala/scalismo/faces/sampling/face/evaluators/LandmarkMapEvaluator.scala
> +class LandmarkMapEvaluator(sdevNoiseModel: Double, maps: LandmarkDetectionMap, renderer: ParametricLandmarksRenderer) extends DistributionEvaluator[RenderParameter] {
`maps` is just a single `detectionMap`?

2017-03-30 15:57 UTC, sschoenborn commented on src/main/scala/scalismo/faces/sampling/face/evaluators/LandmarkMapEvaluator.scala
> +  def apply(sdevNoiseModel: Double, maps: Seq[LandmarkDetectionMap], renderer: ParametricLandmarksRenderer): Unit = {
return value should not be `Unit` but a `ProductEvaluator[RenderParameter]`

2017-03-30 15:58 UTC, sschoenborn commented
I am concerned mainly with the Unit return type in `LandmarkMapEvaluator.apply`

2017-03-31 07:32 UTC, Andreas-Forster commented on src/main/scala/scalismo/faces/landmarks/LandmarkDetectionMap.scala
> +class LandmarkDetectionMap(val tag: String, val map: PixelImage[Double]) {
This will be redesigned to make it only a trait.

2017-03-31 07:33 UTC, Andreas-Forster commented on src/main/scala/scalismo/faces/landmarks/LandmarkDetectionMap.scala
> +  def precalculateIsotropicGaussianNoise(stddevNoiseModel: Double) = {
vanishes in redesigned pull request

2017-03-31 07:33 UTC, Andreas-Forster commented on src/main/scala/scalismo/faces/landmarks/LandmarkDetectionMap.scala
> +  def apply(tag: String, map: PixelImage[Double], fp: Double, fn: Double): LandmarkDetectionMap = {
True.

2017-03-31 07:33 UTC, Andreas-Forster commented on src/main/scala/scalismo/faces/sampling/face/evaluators/LandmarkMapEvaluator.scala
> +class LandmarkMapEvaluator(sdevNoiseModel: Double, maps: LandmarkDetectionMap, renderer: ParametricLandmarksRenderer) extends DistributionEvaluator[RenderParameter] {
Yes its a typo.

2017-03-31 07:34 UTC, Andreas-Forster commented on src/main/scala/scalismo/faces/sampling/face/evaluators/LandmarkMapEvaluator.scala
> +  def apply(sdevNoiseModel: Double, maps: Seq[LandmarkDetectionMap], renderer: ParametricLandmarksRenderer): Unit = {
This was definitively a bug. Thx for the thorough review. Should not make any further pull requests when leaving.

2017-03-31 07:49 UTC, Andreas-Forster commented
The updated pull-request addresses all comments from the reviewers. It should solve most comments and some are now outdated.

2017-03-31 12:44 UTC, sschoenborn approved these changes

2017-03-31 12:45 UTC, sschoenborn commented
Looks good

2017-03-31 12:48 UTC, merged